### ISSUE TITLE
mac os版本10.11.6 启动mongodb数据库时报错

### ISSUE THREAD

**Issue by Terence-Cheng** [page-pipepline/pipeline-document#2]
mongodb_1  | 2019-03-01T03:29:52.339+0000 I STORAGE  [initandlisten] exception in initAndListen: 20 Attempted to create a lock file on a read-only directory: /data/db, terminating

看样子是权限的问题，执行sudo chmod -R 777 /data/db也无法解决

**Comment by Terence-Cheng** [comment]
把mac os版本升级到10.12.6，重新安装docker就好了。但是启动mogodb的时候还是报错，2019-03-05T09:26:57.465+0000 I ACCESS   [conn1] SCRAM-SHA-1 authentication failed for root on admin from client 172.xx.xx.3:43752 ; UserNotFound: Could not find user root@admin

**Comment by Terence-Cheng** [comment]
上面的错误也解决了
先进入docker容器  
$ docker exec -it  \`docker ps -f name=pipeline -q\` bash
再连接mongodb   
 `$ mongo admin`
然后手动创建用户  
`$ db.createUser({ user: 'root', pwd: 'password', roles: [ { role: "userAdminAnyDatabase", db: "admin" } ] });`

**Comment by CntChen** [comment]
厉害!
