### ISSUE TITLE
如何集成用户输入，提交表单的动作呢？

### ISSUE THREAD

**Issue by jinghaoo** [page-pipepline/pipeline-document#4]
请问如何将表单集成进来呢？没弄明白数据的流动

**Comment by CntChen** [comment]
可视化编辑时候的填写表单吗?

表单是自动生成的, 使用 JSON Schema 来生成. 生成的工具是: [json-editor](https://github.com/json-editor/json-editor).

比如: 
[页面全局配置](https://github.com/page-pipepline/pipeline-template-react/blob/master/src/config/base-config-schema.json) 会生成全局配置表单:

![image](https://user-images.githubusercontent.com/4598445/56026343-8ad7c080-5d46-11e9-82e7-c61dd281aacd.png)

**Comment by jinghaoo** [comment]
抱歉，我没说清楚，我指的是用户使用的表单， 并将用户提交的数据存储下来。

**Comment by CntChen** [comment]
“用户使用的表单”这里的用户是页面可视化编辑人员, 还是使用页面的外部用户?

可视化编辑人员使用的表单有两种`页面全局配置`和`各个组件配置`.
外部用户, 需要根据模板添加表单业务组件, 数据提交到自己的后台.

**Comment by jinghaoo** [comment]
指的是使用页面的外部用户,根据模板添加表单业务组件后怎么才能收集到用户输入的数据呢？

**Comment by CntChen** [comment]
这个问题和页面搭建工具无关.
页面请求后台接口获取数据, 然后将数据提交到后台. 就像在淘宝输入框中搜索商品, 商品名称就要提交到后台.
